function   params=CEBRA_defaultParams()
% function params=CEBRA_defaultParams()

params = struct('model_type',           'supervised',       ...
                'mod_arch',             'offset10-model',   ...
                'distance',             'cosine',           ...
                'conditional',          'time_delta',       ...
                'temperature',          1,                  ...       
                'time_offsets',         10,                 ...
                'max_iter',             1000,               ...
                'max_adapt_iter',       500,                ...
                'batch_size',           256,                ...
                'learning_rate',        3e-4,               ...
                'output_dimension',     3,                  ...
                'verbose',              'True',             ...
                'num_hidden_units',     32,                 ...
                'pad_before_transform', 'True',             ...
                'hybrid',               'false'             ...
                );
