#/path/to/input /path/to/output rat_name results.hdf5 /path/to/params.yaml --use_grid


cebra_time:
  fixed:
    model_architecture: 'offset10-model'
    device: 'cuda_if_available'
    conditional: 'time_delta'
    batch_size: 1024
    max_iterations: 4000
    hybrid: False
    distance: 'cosine'
    verbose: True
    time_offsets: 10
    output_dimension: 3
    #learning_rate: 0.0028521675677231
    #num_hidden_units: 64
    #temperature: 3.212991682008965
  grid:

    max_iterations: [2000, 1000, 3000]
    learning_rate: [0.0001,  0.0028521675677231,0.0003]
    num_hidden_units: [32,64]
    temperature: [1, 1.265961499, 2.5, 3.212991682008965]
cebra_behavior:
  fixed:
    model_architecture: 'offset10-model'
    device: 'cuda_if_available'
    conditional: 'time_delta'
    batch_size: 1024
    max_iterations: 5000
    hybrid: False
    verbose: True
    time_offsets: 10
    output_dimension: 3
    learning_rate: 0.0001
    num_hidden_units: 64
    temperature: 1.266
  grid:
    max_iterations: [5000]

    learning_rate: [0.00005,0.0001]
    num_hidden_units: [32,64]
    temperature: [0.5,1,2]

    
    
cebra_hybrid:
  fixed:
    model_architecture: 'offset10-model'
    device: 'cuda_if_available'
    conditional: 'time_delta'
    batch_size: 256
    max_iterations: 1000
    hybrid: True
    verbose: True
    time_offsets: 10
    output_dimension: 3
  grid:
    learning_rate: [0.0003,0.003]
    num_hidden_units: [32, 64]
    temperature: [1, 2, 3]


tsne:
  fixed:
    n_components: 2
    learning_rate: 'auto'
    n_iter: 200
    initialization: 'pca'
    metric: 'cosine'
    theta: 0.5
    n_jobs: -1
    negative_gradient_method: 'fft'
    verbose: True
  grid:
    perplexity: [10, 20]
    early_exaggeration: [10, 16.44, 25]

umap:
  fixed:
    n_neighbors: 24
    n_components: 2
    n_jobs: -1
    min_dist: 0.0001
    n_epochs: 200
    metric: 'euclidean'
    verbose: True
  grid:
    n_neighbors: [12, 24]

conv_pivae:
   fixed:
     dim_z: 2
     gen_nodes: 60
     n_blk: 2
     mdl: 'poisson'
     disc: False
   grid:
     learning_rate: [0.00025, 0.0005, 0.001,  0.002, 0.003]
   fit_params:
     batch_size: 256
     epochs: 200
     verbose: 1
   
