paths:
  main_path: "/media/zlollo/STRILA/CNR_neuroscience/cebra_git/Cebra_for_all/cebra_codes"
  data_folder: "/media/zlollo/STRILA/CNR_neuroscience/cebra_git/Cebra_for_all/data/rat_hippocampus"
  output_folder: "/media/zlollo/STRILA/CNR_neuroscience/cebra_git/Cebra_for_all/cebra_codes"

model_params:
  architecture: "offset10-model"
  batch_size: 512
  learning_rate: 0.0003
  temperature: 1
  output_dimension: 3
  max_iterations: 500
  distance: "cosine"
  conditional: "time_delta"
  hybrid: False
  time_offsets: 10


hd5_specifics:
  #### original data store
  db_name: "rat_data.hdf5"
  group_name: "/Achilles_data"
  neural_data_path : "/Achilles_data/rat_neural"
  behav_data_path : "/Achilles_data/rat_behav"
  
  ### manifold store
  db_manif: "manif_file_1"
  gr_manif1: "/manif_std_div_et_imp"

