#/path/to/input /path/to/output rat_name results.hdf5 /path/to/params.yaml --use_grid


cebra_time:
  fixed:
    model_architecture: 'offset10-model'
    device: 'cuda_if_available'
    conditional: 'time_delta'
    batch_size: 256
    max_iterations: 10000
    hybrid: False
    verbose: True
    time_offsets: 10
    output_dimension: 3
  grid:
    learning_rate: [0.0003, 0.002, 0.003]
    num_hidden_units: [32, 64]
    temperature: [1, 1.5, 2, 2.5, 3, 3.5]

cebra_behavior:
  fixed:
    model_architecture: 'offset10-model'
    device: 'cuda_if_available'
    conditional: 'time_delta'
    batch_size: 256
    max_iterations: 10000
    hybrid: False
    verbose: True
    time_offsets: 10
    output_dimension: 3
  grid:
    learning_rate: [0.0003, 0.002, 0.003]
    num_hidden_units: [32, 64]
    temperature: [1, 1.5, 2, 2.5, 3, 3.5]
    
    
cebra_hybrid:
  fixed:
    model_architecture: 'offset10-model'
    device: 'cuda_if_available'
    conditional: 'time_delta'
    batch_size: 256
    max_iterations: 10000
    hybrid: True
    verbose: True
    time_offsets: 10
    output_dimension: 3
  grid:
    learning_rate: [0.0003, 0.002, 0.003]
    num_hidden_units: [32, 64]
    temperature: [1, 1.5, 2, 2.5, 3, 3.5]

tsne:
  fixed:
    n_components: 2
    learning_rate: 'auto'
    n_iter: 1000
    initialization: 'pca'
    metric: 'cosine'
    theta: 0.5
    n_jobs: -1
    negative_gradient_method: 'fft'
    verbose: True
  grid:
    perplexity: [10, 20]
    early_exaggeration: [10, 16.44, 25]

umap:
  fixed:
    n_neighbors: 24
    n_components: 2
    n_jobs: -1
    min_dist: 0.0001
    n_epochs: 1000
    metric: 'euclidean'
    verbose: True
  grid:
    n_neighbors: [12, 24]

CONV_PIVAE:
  dim_x: X.shape[1]
  dim_z: 2
  dim_u: 3
  time_window: 10
  gen_nodes: 60
  n_blk: 2
  mdl: 'poisson'
  disc: False
  learning_rate: 0.00025
